language: node_js
node_js: '9'
sudo: enabled
dist: trusty
os:
- linux
script:
- yarn test
deploy:
  skip_cleanup: true
  provider: npm
  email: sentialx@gmail.com
  api_key:
    secure: jNuFleG6afUjnfBxnaLORZwGZCZfgaH95iNg/oBY0Fz641gwt0XBvhc9vJ2NoCzk+PuYF+LuhgVpyv7Auy1P7xHEazaOIXKQ3WCFzkcx9aKrouJnhPb1Nj6rIPNGnj+g49T9QE9AwpUENLVSB6NWz9oG2GwvNgPrl2QytaeJ/NcDqSpNMkLYXEhBMvMqjop6mGT0B5so3g3o1Xv7kn+UzyqfKnOFMwMyPTe1IFqWQSPgHWvZcs6qTMu2cignJXaqKPmFqR9p/yLG2/rxARtUjZ/jlTuZgl+EJUq2+nJ49amMmY1B09PJnMq1FNCamUK3QvDo2nYgZZbRqD25eW8GbbHT8XU1KXwotc9WjphqHRzTrUM7vsmdLAFoQ6ntbAmWjL0IhWoDyE61ZZLK96C2DTlca648WeGI87ishrqWVbgkgP2UGXAPUbgSMg7CPe0i1dykGopJk4Ksa1pSXuitn6RwQcGd+sehESDRlXp+ZIayyYAV7b2nD9BFH4z655NaMaFXu+Vg9rJ1FfnTqea2Eg8ei9bffIqkJx2YU6Rxgu0gzRkDUFqFf4wfZdOUlsQLkCTh2QRNLWbSp7wW1tdbJqM/VwaTuOkvCATavZjJ3MXpxacL+zJkZRct1kyOCPg4SSO2ivT89xf4XdoJBkNW7t2tp6Z0lqFyjGbZTVMRGNc=
  on:
    branch: master
