language: node_js
node_js: '9'
sudo: enabled
dist: trusty
os:
- linux
script:
- yarn test
deploy:
  provider: npm
  email: sentialx@gmail.com
  api_key:
    secure: jpxSpcOAhIDnmMOCz/Prqe+6wW2G+lDZU/NUTnCo5x/E0pVr5ibKbDA1XEVhHTGAmB1HdSsVYPDoilueYlyS1zWHCfQMsL8etJpTc2BWwzo9tS7VPC3BGI3idA/hDwXJ9PZuOIbd42ntdVxzrhJ3kiAObjGKPg0VS7CmX2aQBSe6iL8YVpl31+Fmh7PW6oImY+ZZ2YjV4YH8yGDJSIWEXktKpleGyoB0sKhUHIq4+W4ZAxAgQr2QuectRAaunoRaw6IMVSGiO58hvfugsZO5A5nvRVbTrQ3V+NfznHMya+kn437ObktWratUatscn0oKIkBWKYUZefkcKfcN7yfMH6HPb2TMG3yJk700VEUPk4ZL34a5xl3oIpZApXPq1U4XFeLX5wg/InGBJ0ZwSCrW4YOgIy+bGoKK2tbw5uEHftS/xUYuu+3obv9AXNQeJs7tGd1TPwmHbHpwx2GdEVeYrkaclKnxm85KH5OS15urUbPeDwDYcG6EoRnbJigHOwQWR6TuJmWZ9tab4w2je2BgOLaOUEvu7KHaSzndRnQYbd+nvVnNmJLMtTUiIZ/qDCwXMJFUkBt07LhT4unAo1ld0tMgXHsuEFSpnq+j+EotDuyHOCWbOJI+3Ba2u3rHKarrPyDoSqFYxO+Eta5oUFtwaJfmT4vMRDoE4CBzWjAfE4E=
  on:
    branch: master
install:
  - yarn
